--- #YAML:1.0
name: Win32-Process
abstract: Create and manipulate processes
version: 0.15
author:
  - Jan Dubois <jand@activestate.com>
license: perl
requires: 
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
  homepage: http://code.google.com/p/libwin32/
meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Jan Dubois
