--- #YAML:1.0
name: Win32-Process
abstract: Create and manipulate processes
version: 0.17
author:
  - Jan Dubois <jan@jandubois.com>
license: perl
requires:
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/jandubois/win32-process
meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Jan Dubois
